### PR TITLE
Default to Z_BEST_SPEED instead of Z_NO_COMPRESSION (v2)

### PR DESCRIPTION
**Pull request by ianshmean**
For CI testing. Supersedes #17 

cc. @jaakkor2

### CODE REVIEW

**Comment by ianshmean** [comment]
Based on tests passing and [speed impact](https://github.com/JuliaIO/PNGFiles.jl/pull/17#issuecomment-655763358) being minimal, I say we merge

@Drvi ok?

**Comment by ianshmean** [comment]
It'd be good to get this merged and released as 0.3.0. I'll do so tomorrow evening ET unless anyone objects before then

**Comment by Drvi** [comment]
@ianshmean Thanks for merging and a sorry for the late reply. I do think that doing at least some compression is a good idea and that this change presents a reasonable trade-off between size and performance. 

Btw, I've tried to do some more benchmarking on "Lena" test image and I think our compression is somewhat slower than I would expect (sorry for the lame format, I managed to nuke my session):

[lena_timings.txt](https://github.com/JuliaIO/PNGFiles.jl/files/4921327/lena_timings.txt)

**Comment by ianshmean** [comment]
Ah great @Drvi . It's a little hard to get a handle on the effect in those results. I didn't see a big effect though

**Pull request merged**
