### PR TITLE
Support ARGB32 images

### PR DESCRIPTION
**Pull request by timholy**
Fixes https://github.com/JuliaIO/FileIO.jl/issues/352

### CODE REVIEW

**Comment by timholy** [comment]
The "too many files" from that bug is triggered because FileIO falls back to ImageMagick which struggles to do anything properly :smile:. Fix this, and then the saving gets handled by PNGFiles.

**Review by johnnychen94 — APPROVED** [review]
Since this PR fixes a broken use case, perhaps we can mark `ARGB{N0f8}.(x)` as a performance TODO and then merge this?

**Comment by Drvi** [comment]
Hi and thanks for the fix! Just fyi, I managed to get tests passing by applying the following diff to this PR:
```diff
@@ -367,11 +367,11 @@ function _save(png_ptr, info_ptr, image::S;
         end
     else
         image_eltype = eltype(image)
-        if (image_eltype <: BGR || image_eltype <: BGRA || image_eltype <: ABGR)
+        if (image_eltype <: BGR || image_eltype <: BGRA || image_eltype <: ABGR || image_eltype <: ARGB32)
             png_set_bgr(png_ptr)
         end

-        if image_eltype <: AbstractARGB
+        if (image_eltype <: ABGR || image_eltype <: ARGB)
             png_set_swap_alpha(png_ptr)
         end

@@ -455,7 +455,6 @@ end
 _prepare_buffer(x::IndirectArray) = UInt8.(x.index .- first(axes(x.values, 1)))
 _prepare_buffer(x::BitArray) = _prepare_buffer(collect(x))
 _prepare_buffer(x::AbstractMatrix{<:T}) where {T<:Colorant{<:Normed}} = x
-_prepare_buffer(x::AbstractMatrix{ARGB32}) = ARGB{N0f8}.(x)   # unclear why this helps (maybe endianness?)
 _prepare_buffer(x::AbstractMatrix{<:T}) where {T<:UInt8} =  reinterpret(Gray{N0f8}, x)
 _prepare_buffer(x::AbstractMatrix{<:T}) where {T<:UInt16} = reinterpret(Gray{N0f16}, x)
 _prepare_buffer(x::AbstractMatrix{<:T}) where {T<:Normed} = reinterpret(Gray{T}, x)
```
I.e. by not swapping alpha but treating the colorant as BGR. Apparently, libpng treats the bytes in ARGB32 type as BGRA, so alpha is in the right place, it just the BGR that needs to be "swapped to RGB".

**Comment by timholy** [comment]
Thanks, @Drvi! I credited that to you and will make you a co-author of the squashed commit.

**Pull request merged**
