### PR TITLE
Argb support fix

### LINKED ISSUE #8: ARGB support
It works normally for `RGBA` but in `ARGB` case, the saving image is a blue bar 😥 

```julia
img = ARGB.(repeat(colormap("Reds"), 1, 10))
PNGFiles.save("argb_test.png", img)
```

### PR DESCRIPTION
**Pull request by Drvi**
Fixes #8 

In the case of `BGR`, `ARGB`, `BGRA` and `ABGR` represented with floating points we were handling the struct pixel layout twice -- once with libng by calling `png_set_brg` and `png_set_swap_alpha`  and by _converting_ the data layout to `RGBA` in `_prepare_buffer` -- these two operations sort of cancelled each other out. The fix implemented here is not to do the conversions.

cc: @johnnychen94

### CODE REVIEW

**Comment by ianshmean** [comment]
I tried to figure out the resolver error but I'm failing. 
Any ideas @johnnychen94?

**Comment by johnnychen94** [comment]
Thanks for the lighting fix!

A new ColorVectorSpace release with compat fix is needed, see also https://github.com/JuliaGraphics/ColorVectorSpace.jl/pull/122 and https://github.com/JuliaImages/ImageCore.jl/pull/124

It succeeded in nightly because of a Pkg issue, possibly related to https://github.com/JuliaLang/Pkg.jl/issues/1720

This is only a test stage issue, and if it's tested locally with a customed version of ColorVectorSpace, I think it's okay to not wait for a new version of `ColorVectorSpace`

**Comment by kimikage** [comment]
temporary repair?
```
[compat]
ImageCore = "0.8.11"
```

**Comment by kimikage** [comment]
BTW, PNGFiles.jl uses a primitive `Array` as the buffer, so I doubt  that we really need to use `colorview` or depend on ImageCore.jl.

Of course, it is intuitive that PNGFiles.jl depends on ImageCore.jl. However, we faced the dependency issue, so I think the low-level processing looks reasonable.

**Comment by ianshmean** [comment]
I removed the Images dep during test by absorbing absmaxfinite in #10 and rebased this

**Pull request merged**
